const trackDir = "";
const bpm = 122;
const parts = [
    // { file: "1.wav", length: 8, loop: 1 },
    { file: "2.wav", length: 24, loop: 1 }, 
    { file: "2b.wav", length: 8, loop: 1 }, 
    { file: "3b.wav", length: 8, loop: 1 }, 
    { file: "4b.wav", length: 4, loop: 1 }, 
    { file: "5b.wav", length: 2, loop: 1 }, 
    { file: "3.wav", length: 2, loop: 1 }, 
    { file: "3d.wav", length: 4, loop: 1 },
    { file: "4.wav", length: 4, loop: 1 },
    { file: "5.wav", length: 8, loop: 1 },
    { file: "6.wav", length: 8, loop: 1 }, 
    { file: "7.wav", length: 4, loop: 1 },  
    { file: "8.wav", length: 4, loop: 1 },
    { file: "9.wav", length: 4, loop: 1 }, 
    { file: "10.wav", length: 4, loop: 1 }, 
    { file: "11.wav", length: 4, loop: 1 }, 
    { file: "12.wav", length: 4, loop: 1 }, 
    { file: "13.wav", length: 4, loop: 1 }, 
    { file: "14.wav", length: 4, loop: 1 },
    { file: "15.wav", length: 4, loop: 1 }, 
    { file: "16.wav", length: 4, loop: 1 }, 
    { file: "17.wav", length: 4, loop: 1 },
    { file: "18.wav", length: 4, loop: 1 }, 
    { file: "19.wav", length: 4, loop: 1 }, 
    { file: "20.wav", length: 4, loop: 1 },
    { file: "21.wav", length: 4, loop: 1 },
    { file: "22.wav", length: 4, loop: 1 },
    { file: "23.wav", length: 4, loop: 1 },
    { file: "GrandRising-358_original.mp3", length: 54, loop: 1 },
];
const presets = [];
presets.push([    
    
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
]);
presets.push([
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
]);
presets.push([ 
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
]);
presets.push([ 
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
]);

// console.log("PRODUCER: SLUM GOD")
// console.log("LABEL: Housepit CHI | HPIT.info")
// console.log("DEVELOPER: Bryan (Bai-ee) Balli")
// console.log("ABOUT: EditTrax is a collectable digital audio workstation NFT that allows for the non-destructive editing, rendering, and direct downloading of audio .wav files.")
// console.log("LIMITATIONS:")

// console.log("• DOWNLOADS ENABLED IN SAFARI BROWSERS ONLY. MUST BE VIEWING ON HICETNUNC")
// console.log("• Original artist retains all creative rights to any edit created and downloaded")
// console.log("• You are fully encouraged to use downloaded edits in your mix tapes, social content creation and public performances")
// console.log("• You are not allowed to distribute downloaded edits for direct sale or distribution in any way")
// console.log("CONTACT: edittrax@protonmail.com")
// console.log("WEB: EditTrax.nft | .com")


const downloadName = "Grand_Rising_(#358)_Bai-ee_Flip.wav"
const boxHeight = 50; //min height == 40 -> otherwise clickable buttons are to small
const reverseScrolling = false;
